### ISSUE TITLE
Unable to get this working with podman.sock

### ISSUE THREAD

**Issue by firecat53** [containers/prometheus-podman-exporter#10]
Struggling to get this running just on localhost to test it with user `podman.sock`. I'm not sure what to use for `CONTAINER_HOST`` so I assumed the `unix://` prefix and bind mounted the podman socket. Am I missing something obvious here?

    $ podman run -it --rm -e CONTAINER_HOST=unix:///run/podman/podman.sock -v /run/user/1000/podman/podman.sock:/run/podman/podman.sock:Z quay.io/navidys/prometheus-podman-exporter:latest
    2022/07/21 21:14:10 unable to connect to Podman socket: Get "http://d/v4.1.1/libpod/_ping": dial unix /run/podman/podman.sock: connect: permission denied

Thanks!
(Fedora 36, podman 4.1.1)

**Comment by navidys** [comment]
Hi @firecat53 
Use tcp:// instead of unix:// and it will work. 

$ podman system service --time=0 tcp://<ip>:<port>
$ podman run -e CONTAINER_HOST=tcp://<ip>:<port> --network=host -p 9882:9882 quay.io/navidys/prometheus-podman-exporter:latest

**Comment by ranebull** [comment]
working example
```
systemctl start podman
chmod 666 /run/podman/podman.sock
podman run -e CONTAINER_HOST=unix:///run/podman/podman.sock -v /run/podman/podman.sock:/run/podman/podman.sock:ro --network=host -p 9882:9882 quay.io/navidys/prometheus-podman-exporter
```
But it very strange. Exporter need permission only for read. Why exporter requires write permission on podman socker?
I can use tcp socket for podman.sock. But I want not expose tcp socket on server.

**Comment by firecat53** [comment]
> Hi @firecat53 Use tcp:// instead of unix://.
> 
> ```shell
> $ podman system service --time=0 tcp://<ip>:<port>
> $ podman run -e CONTAINER_HOST=tcp://<ip>:<port> --network=host -p 9882:9882 quay.io/navidys/prometheus-podman-exporter:latest
> ```

Sorry, I saw this in the README, but I don't understand. What ip and port should I use? Why do I need to run the `podman system service` command? 

@ranebull I tried your example, but I am running podman as a user and I'm still getting permission denied errors after `chmod 666 /run/user/1000/podman/podman.sock.

Thanks!

**Comment by nivekuil** [comment]
> But it very strange behavior. I think that exporter need permission only for read. Why exporter requires write permission on podman socket?

It needs to write data to the socket to make an HTTP request to get stats

@firecat53 selinux? Try --privileged, mounting the socket gives you a trivial container escape so you need it.

**Comment by Kybeer** [comment]
> > But it very strange behavior. I think that exporter need permission only for read. Why exporter requires write permission on podman socket?
> 
> It needs to write data to the socket to make an HTTP request to get stats
> 
> @firecat53 selinux? Try --privileged, mounting the socket gives you a trivial container escape so you need it.

I have the same issue.

Running Podman under normal user. No SELinux alerts (Permissive mode gives same error)

**Comment by navidys** [comment]
Hi @firecat53, @ranebull 
Its not a good idea to give 666 permission to the socket file, try following command and replace the UID with the user's UID which you are running the container with, this is working under FC36:

```shell
podman run -e CONTAINER_HOST=unix:///run/podman/podman.sock -v /var/run/user/<UID>/podman/podman.sock:/run/podman/podman.sock --user <UID> --security-opt label=disable  quay.io/navidys/prometheus-podman-exporter
```

**Comment by Kybeer** [comment]
> ```shell
> systemctl start --user podman.socket
> ```

Thanks @navidys , it's working.

Do you have any tips on how to best start `systemctl start --user podman.socket` or on boot?

**Comment by Kybeer** [comment]
> ```shell
> podman system service --time=0 tcp://<ip>:<port>
> ```

@firecat53 use any free port on the container host, for example

`podman system service --time=0 tcp://127.0.0.1:9881`

**Comment by firecat53** [comment]
Finally got back and tried this with the updated rootless instructions in `install.md` and it worked, thanks! I think the two tricks were using `--security-opt label=diable` and `--userns=keep-id`.
