### ISSUE TITLE
Pod names are not displayed in all metrics

### ISSUE THREAD

**Issue by kossioni** [containers/prometheus-podman-exporter#101]
Hello,

We need to have the pod name appear in all metrics. Currently only one metric contain the name of the pod and this is the 'podman_container_info'.

It is vital to have the podname in all other metrics so as to display the podname in the chart ledgent in grafana!

That will avoid unnecessary joins of type: 

`join(podman_container_mem_limit_bytes{id=~"$id"}, 1s, podman_container_info{id=~"$id"})`

Thank you!
Georgios

**Comment by kossioni** [comment]
any chance?

**Comment by navidys** [comment]
Hi @kossioni 
Sorry for late reply, I will look into it.

**Comment by kossioni** [comment]
Thank you so much!

**Comment by user357831** [comment]
Hi @navidys ! This feature would be super helpful for netdata users running podman exporter as there is no option to make joins for alerts. Hope you will find some time to fix it.

**Comment by navidys** [comment]
Hi @user357831 

Sure, will look into it.

**Comment by navidys** [comment]
Hi @kossioni , @user357831 
#181 is adding pod_id and pod_name to containers metrics.
