### ISSUE TITLE
Exclude infra containers?

### ISSUE THREAD

**Issue by nivekuil** [containers/prometheus-podman-exporter#11]
**Is your feature request related to a problem? Please describe.**
More of a question, but is it ever useful to monitor infra containers? It's easy enough to filter those but if they never do anything useful then it could be nice to prune them here.

**Comment by navidys** [comment]
Hi @rhatdan 

I'll appreciate your input on this one, do you think it's better to exclude infra containers from the exposed list ?
Not sure but I think the state will be useful.

**Comment by flouthoc** [comment]
Just two cents why not use `!~` to exclude containers matching `*infra*`. I think there can be still be bugs which can be caught by monitoring `infra` containers but not my strict opinion.

See: https://prometheus.io/docs/prometheus/latest/querying/basics/

**Comment by navidys** [comment]
I think the questions was answered therefore closing this.
