### ISSUE TITLE
make `--collector.image` option use less IO and time by not calculating image size on every scrape

### ISSUE THREAD

**Issue by ykuksenko** [containers/prometheus-podman-exporter#114]
**Is your feature request related to a problem? Please describe.**
When the `--collector.image` option is used the scrape time increases significantly along with I/O. For me hundreds of MBs of reads happen on every scrape.

- I am not certain if https://github.com/containers/storage/issues/1060 is required for this to be done. 
  - here uidmap is listed as part of the problem but we have proper uidmap support now and it is still a problem.
- https://github.com/containers/podman/pull/13810 - tried to make size calculation optional in the podman repo for `podman image ls` but the change was reverted before it shipped.

**Describe the solution you'd like**
Do size calculation only when new images are added or detected. (I presume they should not change size without the ID changing).

**Additional context**
Using podman version 4.4.1

**Comment by navidys** [comment]
Hi @ykuksenko 


Added the feature to main branch and will be part of next release.
