### ISSUE TITLE
arm64 images

### ISSUE THREAD

**Issue by woodfairy** [containers/prometheus-podman-exporter#138]
**Is your feature request related to a problem? Please describe.**
It would be really appreciated if there were builds for arm64 architecture.

**Describe the solution you'd like**
Official arm64 builds (I was not able to get them running by building images myself, using same Containerfile but "arm64" as ARCH variable)

Thanks and best regards

**Comment by navidys** [comment]
Hi @woodfairy 
Added (#141).

Available tags:

![image](https://github.com/containers/prometheus-podman-exporter/assets/5696685/ace73e0b-0e75-4506-93ff-8e960b80fb40)
