### ISSUE TITLE
feature: add status change timestamp

### ISSUE THREAD

**Issue by schlauerlauer** [containers/prometheus-podman-exporter#19]
A feature of e.g. `podman ps -a` is to show the relative time of the last state change (`Up 3 minutes ago`).

Would an additional gauge with this timestamp be possible?

Right now I can't detect restart loops because the state is not `exited` long enough for prometheus to notice.

Thanks for this project! :)

**Comment by navidys** [comment]
Hi @schlauerlauer 

#22 will cover this feature request.
