### ISSUE TITLE
Where is the packaged version?

### ISSUE THREAD

**Issue by csuka** [containers/prometheus-podman-exporter#220]
I read the install file, and there's supposed to be a packaged version available on the epel repo.
I've enabled the epel repo on my rhel 8 vm, but and tried installing the podman exporter, but it can't find the package.

```bash
[root@vm-local-1 prometheus-podman-exporter-1.11.0]# sudo dnf -y install prometheus-podman-exporter
Last metadata expiration check: 0:14:20 ago on Sat 23 Mar 2024 11:37:35 AM UTC.
No match for argument: prometheus-podman-exporter
Error: Unable to find a match: prometheus-podman-exporte
```

I also took a look at [the repo files itself](https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/p/), but the package isn't present.

**Comment by navidys** [comment]
Hi @csuka 

Exporter only supports podman v4, v5 therefore its only available for RHEL 9. RHEL 8 is using podman v3.

I will update the install.md as well.

Regards
