### ISSUE TITLE
image names are parsed incorrectly for repositories that have port numbers.

### ISSUE THREAD

**Issue by ykuksenko** [containers/prometheus-podman-exporter#23]
**Describe the bug**
Incorrect parsing of repository name for images

**To Reproduce**
Include a port number in repository name

**Expected behavior**
Port number should be part of repo name not part of tag

**Screenshots**
Example metric from this exporter:
`podman_image_info{id="20091fb4b6c2",repository="registry.test.example.org",tag="5000/example/ipxe"} 1`
The registry name is actually `registry.test.example.org:5000` the image is `example/ipxe` and the tag is not in the parsed value.

**Desktop (please complete the following information):**
 - Fedora 36
 - Podman 4.1.1

**Additional context**
Podman output:
```
# podman images |grep ipxe
registry.test.example.org:5000/example/ipxe                        20220428            20091fb4b6c2  5 days ago     507 MB
```

**Comment by navidys** [comment]
Hi @ykuksenko 
Thanks for reaching, #24 will fix this issue.
