### ISSUE TITLE
[Question] Is there anyway to make this work with podman v3.0.1?

### ISSUE THREAD

**Issue by Skipper0707** [containers/prometheus-podman-exporter#28]
Hello, I'm using Podman on Debian 11 and Podman v4x hasn't been added to the Debian repository yet, however, this project satisfies all of my container monitoring needs, I know you currently only support podman v4x but I was wondering if I use the image version since I have to enable and mount the `podman.sock`, would this exporter work with Podman v3.0.1 in container mode with `podman.sock` enabled and mounted?

**Comment by navidys** [comment]
Hi @Skipper0707 
Thanks for reaching and sorry for the late reply.

Unforetunetaly the exporter won't work with podman v3.0.1.

**Comment by Skipper0707** [comment]
Thank you so much for answering @navidys.

**Comment by yylyyl** [comment]
Hello everyone,
Thanks for the work by @navidys. I made a fork, and backported this project to podman v3.
You may check it [here](https://github.com/yylyyl/prometheus-podman3-exporter) @Skipper0707.
