### ISSUE TITLE
feat: export also container/image labels

### ISSUE THREAD

**Issue by lukasmrtvy** [containers/prometheus-podman-exporter#34]
**Is your feature request related to a problem? Please describe.**
In an environment where the only determining field is a label it hard to visualize metrics 
from prometheus-podman-exporter, because it does not export labels.

**Describe the solution you'd like**
Would be superb to have an option to export also container/image labels, like cAdvisor does:
```
-store_container_labels=false -whitelisted_container_label="com.docker.compose.config-hash,com.docker.compose.container-number,com.docker.compose.oneoff,com.docker.compose.project,com.docker.compose.service"
```

**Additional context**
No

**Comment by navidys** [comment]
Hi @lukasmrtvy 
Sorry for late response.

#61 will add the requested feature and will convert pod/container/image labels to metric variable labels.

```shell
podman_container_info{id="72c08cae0be3",image="docker.io/library/busybox:latest",label02="value02",label03="value03",name="busybox02",pod_id="",ports=""} 1

podman_image_info{id="2bdf8a106d1e",io_buildah_version="1.27.0",parent_id="",repository="localhost/podman-pause",tag="4.2.1-1662580673"} 1

podman_pod_info{id="23038034708e",infra_id="bd7627e4d928",label01="value01",label02="value02",name="pod01"} 1
```
