### ISSUE TITLE
Generate multi-arch Container images

### ISSUE THREAD

**Issue by quentin9696** [containers/prometheus-podman-exporter#58]
**Is your feature request related to a problem? Please describe.**
The published container image is only build for amd64 arch.  This can't run on other arch like raspberry pi 4 with arm64 arch

**Describe the solution you'd like**
Build and publish the container image for multiple arch

**Additional context**
I might work on this but I see any existing pipeline to build and publish the container image

**Comment by navidys** [comment]
Hi @quentin9696 
workflow is added .github/workflows/build-and-publish.yaml to build and publish the container image.
However the workflow is for amd64 , do you still want to work on this ?

**Comment by quentin9696** [comment]
Hi @navidys 

Sure, I can work on that. I don't have free time for now but I'll have more time mid-December to create the PR.

**Comment by navidys** [comment]
Hi @quentin9696 
Sure, thanks.

**Comment by PolonNatal97** [comment]
thanks.

**Comment by t4nki** [comment]
Hi !

Are there any news about this issue ?

Podman and Grafana both run great on a Raspberry Pi and this project would fit nicely between the two

I have absolutely no experience regarding coding, so I would be of absolutely no help, except for testing

Keep the community posted about this

Regards

**Comment by navidys** [comment]
Hi @t4nki 
I will work on it and keep you posted .

**Comment by t4nki** [comment]
> Hi @t4nki I will work on it and keep you posted .

Hi
Thank you for your reply!

**Comment by navidys** [comment]
Hi @quentin9696 @PolonNatal97 @t4nki 

Added (https://github.com/containers/prometheus-podman-exporter/pull/141).

Available tags:

![image](https://github.com/containers/prometheus-podman-exporter/assets/5696685/91f1a215-19e8-45cc-8655-401e0e950758)
