### ISSUE TITLE
Support Ubuntu Jammy 22.04 / 22.10

### ISSUE THREAD

**Issue by dharapvj** [containers/prometheus-podman-exporter#67]
**Is your feature request related to a problem? Please describe.**
Currently, Ubuntu is supporting 3.4.x podman. And podman exporter errors out with 

```
❯ podman run -it -e CONTAINER_HOST=unix:///run/podman/podman.sock -v $XDG_RUNTIME_DIR/podman/podman.sock:/run/podman/podman.sock --userns=keep-id --security-opt label=disable -u 1000 quay.io/navidys/prometheus-podman-exporter
2022/11/24 10:18:27 unable to connect to Podman socket: server API version is too old. Client "4.0.0" server "3.4.4"
```

But the api is accessible and works well.. may be some parts might not work in podman v3.4
e.g.
`curl --unix-socket /run/user/1000/podman/podman.sock http://d/v4.3.1/libpod/info`

**Describe the solution you'd like**
Allow to use podman-exporter even with ubuntu 22.04 / 22.10

**Additional context**

**Comment by navidys** [comment]
Hi @dharapvj 
Unfortunelty not possible and the exporter is only supports podman v4.
