### ISSUE TITLE
noob questions (sorry): How do you filter podman_container_state on value ?

### ISSUE THREAD

**Issue by uinguzero** [containers/prometheus-podman-exporter#77]
again sorry for the noob question here

so i just want to do this

podman_container_state=2

so it only shows me the running containers.

i've looked at examples of other querys, like cpu times and it just states the metrics name and then the value like

cpu_memory_time>300

but i can't get it wokring with the podman_container_state

**Comment by felixkrohn** [comment]
What you're looking for probably is `==` instead of `=`?
To make the output more useful you can also add the container's name like that:
`podman_container_state * on (id) group_left(name) podman_container_info == 2`
